[manager]
cwd = { fg = "white", bold = true }

hovered = { fg = "white", bg = "black", bold = true }
preview_hovered = { fg = "white", bg = "black" }

find_keyword = { fg = "white", bold = true }
find_position = { fg = "white" }

marker_selected = { fg = "white", bold = true }
marker_copied = { fg = "white" }
marker_cut = { fg = "white" }

tab_active = { fg = "white", bg = "black", bold = true }
tab_inactive = { fg = "white" }

border_symbol = "|"
border_style = { fg = "white" }

[status]
separator_open = ""
separator_close = ""

mode_normal = { fg = "white", bg = "black", bold = true }
mode_select = { fg = "white", bg = "black", bold = true }
mode_unset = { fg = "white", bg = "black", bold = true }

progress_label = { fg = "white" }
progress_normal = { fg = "white", bg = "black" }

[preview]
border = { fg = "white" }

[filetype]
rules = [
  { mime = "image/*", fg = "white" },
  { mime = "text/*", fg = "white" },
]
