[manager]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"
layout = [ 1, 3, 4 ]

[opener]
edit = [
    { run = 'vim "%s"', block = true, desc = "Edit with Vim" }
]
extract = [
    { run = '7z x "%s"', block = true, desc = "Extract with 7z" }
]
display = [
    { run = 'swayimg "%s"', orphan = true, desc = "Open Image" }
]
video = [
    { run = 'mpv "%s"', orphan = true, desc = "Play Video with mpv" }
]
audio = [
    { run = 'mpv --force-window "%s"', orphan = true, desc = "Play Audio with mpv" }
]
browser = [
    { run = 'xdg-open "%s"', orphan = true, desc = "Open in Browser" }
]

[open]
rules = [
    { mime = "image/*", use = ["display"] },
    { mime = "video/*", use = ["video"] },
    { mime = "audio/*", use = ["audio"] },
    { mime = "text/*",  use = ["edit"] },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract"] },

    { url = "*.pdf",  use = ["browser"] },
    { url = "*.mkv",  use = ["video"] },
    { url = "*.mp4",  use = ["video"] },
    { url = "*.avi",  use = ["video"] },
    { url = "*.mov",  use = ["video"] },
    { url = "*.webm", use = ["video"] },

    { url = "*.sh",   use = ["edit"] },
    { url = "*.conf", use = ["edit"] },
    { url = "*.yaml", use = ["edit"] },
    { url = "*.yml",  use = ["edit"] },
    { url = "*.json", use = ["edit"] },
    { url = "*.toml", use = ["edit"] },

    { url = "*",      use = ["edit"] }
]
