[manager]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"
layout = [ 1, 3, 4 ]

[opener]
edit = [
    { run = 'vim %s', block = true, desc = "Edit with Vim" }
]
extract = [
    { run = '7z x %s', block = true, desc = "Extract with 7z" }
]
display = [
    { run = 'swayimg %s', orphan = true, desc = "Open Image in swayimg" }
]
video = [
    { run = 'mpv %s', orphan = true, desc = "Play Video with mpv" }
]
audio = [
    { run = 'mpv --force-window %s', orphan = true, desc = "Play Audio with mpv" }
]

[open]
prepend_rules = [
    { mime = "image/*", use = "display" },
    { url = "*.{jpg,jpeg,png,webp,gif,svg,bmp}", use = "display" },

    { mime = "video/*", use = "video" },
    { url = "*.{mp4,mkv,avi,mov,webm,flv}", use = "video" },

    { mime = "audio/*", use = "audio" },
    { url = "*.{mp3,flac,wav,ogg,m4a,opus,aac}", use = "audio" },

    { url = "*.{sh,conf,yaml,yml,json,toml}", use = "edit" }
]
