[manager]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"
layout = [ 1, 3, 4 ]

prepend_keymap = [
    { on = [ "D" ],       run = "remove --permanently --force", desc = "Delete forever" },
    { on = [ "<Enter>" ], run = "open",                         desc = "Open the selected files" },
    { on = [ "s" ],       run = "search fd",                     desc = "Search files by name (fd)" }
]

[opener]
edit = [
    { run = 'vim "$@"', block = true, for = "unix" }
]
extract = [
    { run = '7z x "$1"', block = true, desc = "Extract with 7z", for = "unix" }
]
display = [
    { run = 'swayimg "$@"', orphan = true, desc = "Open" }
]
video = [
    { run = 'mpv --force-window "$@"', block = false, desc = "Play with mpv" }
]
audio = [
    { run = 'mpv --force-window "$@"', block = false, desc = "Play Audio with mpv" }
]
browser = [
    { run = 'xdg-open "$@"', desc = "Open in Browser", detach = true }
]

[open]
rules = [
    { mime = "image/*", use = ["display"] },
    { mime = "image/webp", use = ["display"] },
    { mime = "video/*", use = ["video"] },
    { mime = "audio/*", use = ["video"] },
    { mime = "text/*", use = ["edit"] },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract"] },
    { mime = "audio/*", use = ["audio"] },

    { name = "*.pdf",  mime = "*", use = ["browser", "reveal"] },
    { name = "*.mkv",  mime = "*", use = "video" },
    { name = "*.mp4",  mime = "*", use = "video" },
    { name = "*.avi",  mime = "*", use = "video" },
    { name = "*.mov",  mime = "*", use = "video" },
    { name = "*.webm", mime = "*", use = "video" },

    { name = "*.conf", mime = "*", use = ["edit"] },
    { name = "*.yaml", mime = "*", use = ["edit"] },
    { name = "*.json", mime = "*", use = ["edit"] },
    { name = "*.yml",  mime = "*", use = ["edit"] },
    { name = "*",      mime = "*", use = "edit" }
]
