hl.config({ autogenerated = false })

hl.monitor({ output = "your-monitor", mode = "preferred", position = "auto", scale = 1 })

local terminal = "kitty"
local fileManager = "kitty -e yazi"
local menu = "rofi -show drun -theme ~/.config/rofi/config.rasi"
local screenshot = [[sh -c 'grim -g "$(slurp -b 00000000 -s 00000011 -c 00000000 -w 0)" - | wl-copy']]

hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("ADW_DISABLE_PORTAL", "1")
hl.env("GTK_THEME", "Orchis-Dark")

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Orchis-Dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'")
    hl.exec_cmd("cliphist wipe")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "grp:alt_shift_toggle",
        follow_mouse = 1,
        sensitivity = 0.2,
        accel_profile = "flat",
        repeat_rate = 50,
        repeat_delay = 250,
    },
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        ["col.active_border"] = "rgba(ffffffff)",
        ["col.inactive_border"] = "rgba(00000000)",
        layout = "dwindle",
    },
    decoration = {
        rounding = 10,
        shadow = {
            enabled = false,
        },
        blur = {
            enabled = true,
        },
    },
    animations = {
        enabled = true,
    },
})

hl.curve("smoothSnap",   { type = "bezier", points = { {0.2, 1}, {0.1, 1} } })
hl.curve("popupExpress", { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })

hl.animation({ leaf = "windows",          enabled = true, speed = 7, bezier = "popupExpress", style = "popin 85%" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 7, bezier = "popupExpress", style = "popin 85%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 6, bezier = "smoothSnap",   style = "popin 80%" })

hl.animation({ leaf = "layers",           enabled = true, speed = 6, bezier = "popupExpress", style = "popin 80%" })

hl.animation({ leaf = "fade",             enabled = true, speed = 6, bezier = "smoothSnap" })
hl.animation({ leaf = "border",           enabled = true, speed = 8, bezier = "smoothSnap" })

hl.animation({ leaf = "workspaces",       enabled = true, speed = 9, bezier = "smoothSnap",   style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 9, bezier = "smoothSnap",   style = "slidevert" })

hl.bind("SUPER + Q", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER + E", hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER + S", hl.dsp.exec_cmd(screenshot))
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind("SUPER + Z", hl.dsp.exec_cmd("kitty -e btop"))

hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("pkill rofi || " .. menu), { release = true })

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.window_rule({ name = "mpv-float", match = { class = "mpv" }, float = true })
hl.window_rule({ name = "mpv-center", match = { class = "mpv" }, center = true })
hl.window_rule({ name = "mpv-size", match = { class = "mpv" }, size = { 1200, 720 } })
