monitor=,preferred,auto,0x0,1

$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun -theme ~/.config/rofi/config.rasi
$screenshot = grim -g "$(slurp)" - | magick - -shave 3x3 - | wl-copy 

exec-once = waybar
exec-once = awww-daemon && sleep 0.5 && awww img ~/Pictures/tux.png
exec-once = dunst
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

input {
    kb_layout = us
    kb_options = grp:alt_shift_toggle
    follow_mouse = 1
    sensitivity = 0.2
    accel_profile = flat
    repeat_rate = 50
    repeat_delay = 250
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(ffffffff)
    col.inactive_border = rgba(00000000)
    layout = dwindle
}

decoration {
    rounding = 10
    shadow {
        enabled = false
    }
    blur {
        enabled = true
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    animation = windows, 1, 7, myBezier, popin 80%
    animation = windowsIn, 1, 7, myBezier, popin 80%
    animation = windowsOut, 1, 5, myBezier, popin 80%
    animation = fade, 1, 7, myBezier
    animation = workspaces, 1, 7, easeOutExpo, slide
    animation = specialWorkspace, 1, 6, myBezier, fade
}

$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, S, exec, $screenshot

bindr = $mainMod, SUPER_L, exec, pkill rofi || $menu

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

windowrule = match:class mpv, float 1
windowrule = match:class mpv, center 1
windowrule = match:class mpv, size 1200 720

env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland;xcb
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
